### ISSUE TITLE
Fastboot.require `dist/node_modules`

### ISSUE THREAD

**Issue by xg-wang** [ember-fastboot/fastboot#198]
Fastboot is `require`ing from `...dist/node_modules` before falling back to require(moduleName). [src](https://github.com/ember-fastboot/fastboot/blob/v1.2.0/src/ember-app.js#L124) 
Is this an expected behavior or should the modules be assumed to locate at same level as `dist`?

And the `existsSync` should probably be replaced with `require` wrapped by try-catch directly.

I found this behaviour when debugging an issue [here](https://github.com/ember-cli/ember-fetch/issues/115).
A reproduction can be found at https://github.com/xg-wang/fastboot-issue to demonstrate.

**Comment by rwjblue** [comment]
RE: existsSync I agree (otherwise you have to deal with too many variances RE extension, exactly hierarchy, etc)

**Comment by rwjblue** [comment]
The current behavior of requiring from within dist is correct (modulo the fact that we should be using `resolve.sync` instead of `existsSync`). 

The specific code has some assumptions:

* the thing being required is a top level package name (this is when the current existsSync would work fine). In the demo, this assumption is broken and therefore we hit the else case. This should be migrated to using `resolve.sync`, which would allow deep requires of specific files.
* that the dist has a `node_modules` structure which includes the runtime packages that are required by the app, I don’t think this should go away, but we should document it a bit better. 

most of which will be fixed by using `resolve.sync`),
