### ISSUE TITLE
Unable to fetch assets after Ember 2.7 upgrade 

### ISSUE THREAD

**Issue by claire-lee** [ember-fastboot/fastboot#80]
After upgrading to Ember 2.7 (which included the [deprecation of baseURL](http://emberjs.com/blog/2016/04/28/baseURL.html)) and starting an Ember app using Fastboot, the app tries to retrieve assets based on the rootURL specified, e.g.

- rootURL/assets/vendor.css
- rootURL/assets/appName.js

However, Fastboot is still serving these assets from

- assets/vendor.css
- assets/appName.js

This causes the assets not to be loaded.

I mentioned the issue [here](https://github.com/ember-fastboot/fastboot-express-middleware/issues/12) too, but am wondering if it's an issue with Fastboot itself.

**Comment by danmcclain** [comment]
In the rendered page, do the asset tags have the correct URL (I'm assuming they do, since fastboot doesn't generate them). As long as they do, this is a fastboot-express-middleware issue (which you mention), since fastboot itself does not server the files, it just renders the HTML. If that's the case, we can close this one in favor of https://github.com/ember-fastboot/fastboot-express-middleware/issues/12

Sorry i haven't had time to dig into this more

**Comment by claire-lee** [comment]
Yes, the asset tags have the correct url when using `rootURL`, e.g. 
```
<link rel="stylesheet" href="{{rootURL}}assets/vendor.css">
<link rel="stylesheet" href="{{rootURL}}assets/app-name.css">
```
Will close this issue in favor of the other one.
